spring:
  application:
    name: springcloud-eureka-demo
  security:
    user:
      name: root
      password: admin

server:
  port: 8762

eureka:
  instance:
    hostname: eureka8762
  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 10000
  client:
    #是否需要向注册中心注册 eureka-server 不需要
    register-with-eureka: true
    #是否需要检索服务
    fetch-registry: true
    service-url:
      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@eureka8761:8761/eureka/,http://${spring.security.user.name}:${spring.security.user.password}@eureka8763:8763/eureka/
