spring:
  application:
    name: springcloud-eureka-provider

server:
  port: 8081

eureka:
  client:
    service-url:
      defaultZone: http://root:admin@eureka8761:8761/eureka/,http://root:admin@eureka8762:8762/eureka/,http://root:admin@eureka8763:8763/eureka/